.PHONY: clean All

All:
	@echo "----------Building project:[ lastengine3d - Debug_Win32 ]----------"
	@"$(MAKE)" -f  "lastengine3d.mk"
clean:
	@echo "----------Cleaning project:[ lastengine3d - Debug_Win32 ]----------"
	@"$(MAKE)" -f  "lastengine3d.mk" clean
